services:
  agendador:
    build: .
    container_name: agendador
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/db_agendador
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=senha
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:15-alpine
    container_name: db_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_agendador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
